name: SimplisticEconomy
version: 1.0
main: net.megaplanet.simplisticeconomy.SimplisticEconomy
load: STARTUP
softdepend: [Vault]
commands:
  pay:
  eco:
  money:
  bal:
  balance:
  balancetop:
  baltop:
  moneytop: